# Generated by Django 5.1.1 on 2024-10-03 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_name',
            field=models.CharField(default=datetime.datetime(2024, 10, 3, 6, 41, 26, 88953, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
