# Generated by Django 5.1.1 on 2024-10-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
